[package]
name = "uniform-cubic-splines"
version = "0.1.8"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2021"
readme = "README.md"
keywords = ["splines", "curves", "graphics", "inversion", "cubic"]
categories = ["mathematics", "graphics", "multimedia", "no-std"]
license = "MIT OR Apache-2.0 OR Zlib"
description = "Simple uniform cubic spline evaluation and inversion."
documentation = "https://docs.rs/uniform-cubic-splines/"
repository = "https://github.com/virtualritz/uniform-cubic-splines/"

[dependencies]
num-traits = "0.2"
lerp = "0.5"
# Enable the is_sorted check on spline_inverse()
is_sorted = { version = "0.1", default-features = false, optional = true }

[dev-dependencies]
rand = "0.8"

[features]
default = ["monotonic_check", "std"]
unstable = ["is_sorted/unstable"]
std = ["is_sorted/use_std"]
monotonic_check = ["is_sorted"]

[profile.bench]
debug = true
